### ISSUE TITLE
  TypeError: Cannot read property 'timeout' of undefined

### ISSUE THREAD

**Issue by supasheva** [sesesmith30/ghanapost-address#9]
Hi. I am a fan of this tool and looking forward to see it progress further. I got an error recently when testing out the package.

`[
  TypeError: Cannot read property 'timeout' of undefined
      at Object.exports.grabAddressInfo (node_modules/ghpost-address/app.js:49:140)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
]`

**Comment by supasheva** [comment]
Ok  realised the issue was me not adding the timeout option. Have made a PR for updating the README in case someone else makes the same mistake I did.
